"""usuarios y roles

Revision ID: 8bf6e7b1cdcf
Revises: fdd4d4e7d312
Create Date: 2026-09-27 00:18:45.673001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf6e7b1cdcf'
down_revision: Union[str, Sequence[str], None] = 'fdd4d4e7d312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('asesor', 'administrador', name='user_role'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_users_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.add_column('count_entries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_count_entries_user_id'), 'count_entries', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_count_entries_user_id_users'), 'count_entries', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('count_sessions', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_count_sessions_created_by_id_users'), 'count_sessions', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_count_sessions_created_by_id_users'), 'count_sessions', type_='foreignkey')
    op.drop_column('count_sessions', 'created_by_id')
    op.drop_constraint(op.f('fk_count_entries_user_id_users'), 'count_entries', type_='foreignkey')
    op.drop_index(op.f('ix_count_entries_user_id'), table_name='count_entries')
    op.drop_column('count_entries', 'user_id')
    op.drop_table('users')
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
