"""esquema inicial

Revision ID: fdd4d4e7d312
Revises: 
Create Date: 2026-09-26 23:43:07.217914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd4d4e7d312'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=True),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_unit', sa.String(length=60), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('color_code', sa.String(length=20), nullable=True),
    sa.Column('color_name', sa.String(length=80), nullable=True),
    sa.Column('source', sa.Enum('catalog', 'stock', 'manual', name='product_source'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('ean', name=op.f('uq_products_ean')),
    sa.UniqueConstraint('reference', name=op.f('uq_products_reference'))
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('code', name=op.f('uq_stores_code'))
    )
    op.create_table('stock_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_stock_snapshots_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_snapshots'))
    )
    op.create_index(op.f('ix_stock_snapshots_effective_at'), 'stock_snapshots', ['effective_at'], unique=False)
    op.create_index(op.f('ix_stock_snapshots_store_id'), 'stock_snapshots', ['store_id'], unique=False)
    op.create_table('count_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='session_status'), nullable=False),
    sa.Column('baseline_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_snapshot_id'], ['stock_snapshots.id'], name=op.f('fk_count_sessions_baseline_snapshot_id_stock_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_count_sessions_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_count_sessions'))
    )
    op.create_index(op.f('ix_count_sessions_store_id'), 'count_sessions', ['store_id'], unique=False)
    op.create_table('stock_snapshot_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_snapshot_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['stock_snapshots.id'], name=op.f('fk_stock_snapshot_lines_snapshot_id_stock_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_snapshot_lines')),
    sa.UniqueConstraint('snapshot_id', 'product_id', name=op.f('uq_stock_snapshot_lines_snapshot_id'))
    )
    op.create_index(op.f('ix_stock_snapshot_lines_snapshot_id'), 'stock_snapshot_lines', ['snapshot_id'], unique=False)
    op.create_table('count_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('scanned_code', sa.String(length=40), nullable=True),
    sa.Column('counted_by', sa.String(length=80), nullable=True),
    sa.Column('zone', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_count_entries_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['count_sessions.id'], name=op.f('fk_count_entries_session_id_count_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_count_entries'))
    )
    op.create_index(op.f('ix_count_entries_product_id'), 'count_entries', ['product_id'], unique=False)
    op.create_index(op.f('ix_count_entries_session_id'), 'count_entries', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_count_entries_session_id'), table_name='count_entries')
    op.drop_index(op.f('ix_count_entries_product_id'), table_name='count_entries')
    op.drop_table('count_entries')
    op.drop_index(op.f('ix_stock_snapshot_lines_snapshot_id'), table_name='stock_snapshot_lines')
    op.drop_table('stock_snapshot_lines')
    op.drop_index(op.f('ix_count_sessions_store_id'), table_name='count_sessions')
    op.drop_table('count_sessions')
    op.drop_index(op.f('ix_stock_snapshots_store_id'), table_name='stock_snapshots')
    op.drop_index(op.f('ix_stock_snapshots_effective_at'), table_name='stock_snapshots')
    op.drop_table('stock_snapshots')
    op.drop_table('stores')
    op.drop_table('products')
    sa.Enum(name='session_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='product_source').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
