"""ventas durante el conteo

Revision ID: 1e2d01aa2464
Revises: 8bf6e7b1cdcf
Create Date: 2026-09-27 11:13:34.037247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2d01aa2464'
down_revision: Union[str, Sequence[str], None] = '8bf6e7b1cdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Postgres necesita el tipo ENUM antes de la columna; las filas existentes quedan como
    # lecturas de conteo gracias al server_default.
    entry_kind = sa.Enum('count', 'sale', name='entry_kind')
    entry_kind.create(op.get_bind(), checkfirst=True)
    op.add_column('count_entries', sa.Column('kind', entry_kind, server_default='count', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('count_entries', 'kind')
    sa.Enum(name='entry_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
